# Generated by Django 5.1.4 on 2024-12-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumreview',
            name='score',
            field=models.CharField(choices=[('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10')], max_length=5),
        ),
    ]
